### ISSUE TITLE
缺失index_bundle.js，无法完成编译

### ISSUE THREAD

**Issue by BecodReyes** [LF112/BTCO#7]
```
yarn build
yarn run v1.17.3
$ webpack --mode production
D:\Project\BTCO\pluginMain\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

Error: ENOENT: no such file or directory, open 'D:\Project\BTCO\pluginMain/dist/index_bundle.js'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at Object.<anonymous> (D:\Project\BTCO\pluginMain\webpack.config.js:21:24)
    at Module._compile (D:\Project\BTCO\pluginMain\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (D:\Project\BTCO\pluginMain\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (D:\Project\BTCO\pluginMain\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (D:\Project\BTCO\pluginMain\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at D:\Project\BTCO\pluginMain\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (D:\Project\BTCO\pluginMain\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at D:\Project\BTCO\pluginMain\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (D:\Project\BTCO\pluginMain\node_modules\yargs\yargs.js:567:18)
    at D:\Project\BTCO\pluginMain\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (D:\Project\BTCO\pluginMain\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\Project\BTCO\pluginMain\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:\\Project\\BTCO\\pluginMain/dist/index_bundle.js'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
经查询.gitignore文件内存在/dist忽略规则，导致文件缺失无法完成编译
解决方法：
pluginMain/webpack.config.js
```
#21
-            script: fs.readFileSync(__dirname + '/dist/index_bundle.js'),
+            script: fs.readFileSync(__dirname + '/src/index.js'),

```
希望作者大大能够尽快修复

**Comment by LF112** [comment]
感谢反馈，已经重新更新仓库。

该问题可以通过创建 dist/index_bundle.js 空文件修复。

**Comment by LF112** [comment]
@BecodReyes 这里没有采用您提供的解决方案，script 必须为 webpack 构建之后的文件，原因是：可以使 HtmlWebpackPlugin 在 webpack 打包结束时将构建完成的 JavaScript 文件插入到 BTCO/index.html 文件里。否则使用 webpack 打包毫无意义。目前的方案为暂定方案，期待更佳的解决方案。感谢反馈！
